name: Deploy Project

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20.x
    steps:
      - name: Checkout Repository
      - uses: action/checkout@4

      - name: Install dependencies
      - run: npm ci

      - name: Build Project
      - run: npm run build

      - name: Final
      - run: echo "Deploy into Azure completed succefully"
